["protostar.config"]
protostar_version = "0.2.0"

["protostar.project"]
libs_path = "lib"

["protostar.contracts"]
generic = [
    "./src/onlydust/stream/generic.cairo",
]

default_implementation = [
    "./src/onlydust/stream/default_implementation.cairo",
]
